### ISSUE TITLE
BottomSheet do not appear

### ISSUE THREAD

**Issue by matteovisotto** [aniltaskiran/exampleBottomSheet#2]
I have created the bottom sheet class and associated it to a storyboard view controller. In the main view (A view controller inside a TabBar), when I call the addBottomSheetView() nothing happen. Have I to create the xib file?

**Comment by aniltaskiran** [comment]
if you call it on view controller as I did yes you need to create xib file for bottom sheet. If you want to call it from storyboard you need to instantiateViewController from storyboard

**Comment by matteovisotto** [comment]
Thanks I resolved
